name: Update README - last activity

on:
  schedule:
    - cron: '* */24 * * *'
  workflow_dispatch:

jobs:
  build:
    name: Update this repo's README with recent activity
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          GH_USERNAME: huluvu424242
          COMMIT_MSG: 'Update my activities.'
          MAX_LINES: 10
          
          
